### ISSUE TITLE
Move the `fn.getbufvar(buf, "&modifiable") == 1` condition out of config

### ISSUE THREAD

**Issue by primeapple** [okuuva/auto-save.nvim#12]
Currently if the user wants to add a condition when to enable autosave (only certain filetypes, etc.) he has to use the `condition` field in the config.

This field is already populated by default, and contains a check for `fn.getbufvar(buf, "&modifiable") == 1`. For me this should never be changed by the user anyways, so we can safely move it out of the config, into the `save` function in `init.lua`.

**Comment by okuuva** [comment]
Fixed with #16. Nice job!
