### ISSUE TITLE
The dim setting doesn't work when the plugin is lazy-loaded

### ISSUE THREAD

**Issue by jqno** [okuuva/auto-save.nvim#26]
Here's my lazy.nvim config:

```lua
return {
    'okuuva/auto-save.nvim',
    event = 'BufRead',

    opts = {
        execution_message = {
            dim = 0.4,
            cleaning_interval = 1000
        }
    }
}
```

The value of the dim setting doesn't work. This is because it's only read when `VimEnter`, `ColorScheme` or `UIEnter` is triggered:
https://github.com/okuuva/auto-save.nvim/blob/19bd29c150274e3283ea28d88600e40d14c28803/lua/auto-save/init.lua#L151

Since I'm loading the plugin at `BufRead`, this happens after any of these events (unless I manually change the colorscheme later).

Also, I can't manually set the `AutoSaveText` highlight as a workaround, because that's only configured when `dim` is read.

**Comment by primeapple** [comment]
Thanks for the Report.

You are indeed right with your assumptions. I'll provide a PR to fix this.

**Comment by jqno** [comment]
Awesome, it works perfectly now. Thank you!
