### ISSUE TITLE
config is ignored

### ISSUE THREAD

**Issue by Senaxius** [okuuva/auto-save.nvim#30]
When I add this:
```
  {
    "okuuva/auto-save.nvim",
    cmd = "ASToggle",
    opts = {
      enabled = false
    },
  },

```
to my lazy config, auto-save works just fine, but it always starts enabled. 

I also tried running this setup:
```
require('auto-save').setup {
    enabled = false
}
```
in a seperate file, but got the same results.

What am I doing wrong?

**Comment by primeapple** [comment]
Thanks for filing this issue.
You are completely right, we don't take that parameter into account at the right place. This is yet another left over from the original plugin.

Will see what I can, in the mean time, a `require("auto-save").off()` after the setup should do the trick.

**Comment by zedgamer9128** [comment]
I've tried the latest plugin and this still doesn't work
![image](https://github.com/okuuva/auto-save.nvim/assets/33319711/6461be00-5848-4fbb-91b7-32c28367ef43)

**Comment by okuuva** [comment]
> I've tried the latest plugin and this still doesn't work ![image](https://user-images.githubusercontent.com/33319711/256543741-6461be00-5848-4fbb-91b7-32c28367ef43.png) it still starts enabled and config does not work

Weird, "works on my machine". What does your `lazy-lock.json` say? Mine is at `  "auto-save.nvim": { "branch": "main", "commit": "895bde43d24a52536ae9c258df61b74a69b18b67" },` and like said, works fine here.

Could you elaborate on "config does not work"? What exactly doesn't work?

**Comment by zedgamer9128** [comment]
Sorry It worked just needed to update

**Comment by yongleyuan** [comment]
> I've tried the latest plugin and this still doesn't work ![image](https://private-user-images.githubusercontent.com/33319711/256543741-6461be00-5848-4fbb-91b7-32c28367ef43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjU1NTEsIm5iZiI6MTcyNTQ2NTI1MSwicGF0aCI6Ii8zMzMxOTcxMS8yNTY1NDM3NDEtNjQ2MWJlMDAtNTg0OC00ZmJiLTkxYjctMzJjMjgzNjdlZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE1NTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzdjMzA4Y2UxNzYyMDk5ZGEyY2VhMzIzOGUzOGE4NGIyYjMxMTk5YWIzNTc0NDdjYzVhMzcwZDhjNDM5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DsZtgvS65p3a_uhMZJafbr1-SDPucr7nQxb5fdjgdJo) it still starts enabled and config does not work

I am again facing the same issue with the latest version. Had to manually set `require("auto-save").off()` to turn off auto-save at startup. This works fine, but any reason why this happens?
