### ISSUE TITLE
auto-save enabled at startup even when enabled=False

### ISSUE THREAD

**Issue by bendavis78** [okuuva/auto-save.nvim#38]
I don't want autosave to be enabled at startup, so I configured like so in my lazy.nvim config:

```lua
  {"okuuva/auto-save.nvim", cmd="ASToggle", event="VeryLazy", opts={enabled=false}},
```

However, auto-save is still enabled when starting.

**Comment by primeapple** [comment]
Something similar was fixed some time ago https://github.com/okuuva/auto-save.nvim/issues/30

Can you check the version of your plugin?

**Comment by primeapple** [comment]
@bendavis78 can we get some feedback? Otherwise I suggest closing this one.

**Comment by bendavis78** [comment]
Hi, sorry for the late reply. It works now, thanks!
