### ISSUE TITLE
Different `trigger_events` for different `FileType`s

### ISSUE THREAD

**Issue by Andrew15-5** [okuuva/auto-save.nvim#40]
Original issue: https://github.com/pocco81/auto-save.nvim/issues/80.

@primeapple, is there any progress on this, or it was never brought up here?

<details><summary>P.S.</summary>

I first tested this fork a long time ago, and it didn't work. Now I've tested it again, and it did work, but only after waiting for a second. Anyway, I've tried checking if I can actually do the thing in the title, only to realize that it is not yet implemented.

</details>

**Comment by primeapple** [comment]
Hi @Andrew15-5 
Your idea was not implemented yet. But I think it should be possible.

One idea I had was to use the `pattern` option of `nvim_create_autocmd`. We would have to define a nice way how users would define that in the config.

Another way would be to give some kind of metadata of the triggered autocommand to the `condition` function. That sounds clumsy however.
Will think about it a bit more.

**Comment by Andrew15-5** [comment]
> This is so you don't save to much

You mean to reduce writing operations on SSD? I don't think it's an issue in real world scenario. I don't save anything, the point is to automatically save changes. I always used InsertLeave and TextChanged, and it's more than enough. So, the delay, defer_save and cancel_defered_save seems useless to me.

> If something does not work

Although everything seems to work (except this issue), I do have one problem, but I don't know if we can find a solution.

**Comment by primeapple** [comment]
> You mean to reduce writing operations on SSD? I don't think it's an issue in real world scenario.

There are definitely reasons why you don't want to save to much. Think of external file watchers (bundlers, compilers, testrunners, etc.) If you save after every event they might crash or get confused. Also some people after Callbacks on save for example for formatting.

I'm curious if there is a situation where the delay brings any disadvantage. Anyways, you can just put every event you want into the `immediate_save` events and leave the others empty and that's it.

For your filetype specific events, I'll provide a PR.

**Comment by primeapple** [comment]
Hey @Andrew15-5

I finally found some time to do this.
Feel free to play around with it on the PR branch.
You may need to add the following to your config:

```lua
 trigger_events = {
    defer_save = {
      { "InsertLeave", "TextChanged", { "TextChangedI", pattern = "*.typ"} }
    }
  }
```

Feel free to try it out.

**Comment by Andrew15-5** [comment]
Great! I will try this later. Is `pattern` the only option that will be available? I think the best way is to also add `filetype` option just for convenience. And if both are provided, then use both. Like this:

```lua
  trigger_events = {
    defer_save = {
      { "InsertLeave", "TextChanged", { "TextChangedI", pattern = "*.typ", filetype = { "markdown" } }
    }
  }
```

I don't know if `pattern` can accommodate multiple file extensions, if not, then maybe allow both `pattern` and `filetype` to have a string type or table (list of strings). Maybe this will require to rename options to `patterns` and `filetypes`, but I don't know which one is better.

**Comment by primeapple** [comment]
We are using `Autocommands` under the hood. They do only support patterns. I really don't want to pollute the code more with custom logic, that is only plugin specific. `pattern` should do the trick here and is well tested and the usual way how to define file specific autocommands.

I'd suggest you try `pattern` first, then we'll see :)

**Comment by Andrew15-5** [comment]
Well, I tried it and it works. But it still has to have an ability to receive multiple patterns for different filetypes, or the user will have to duplicate the whole table just to add a second filetype for the same event(s).

**Comment by primeapple** [comment]
Check the README in the PR. You can provide multiple pattern like this.

```lua
{
  trigger_events = {
    immediate_save = {
      { "BufLeave", pattern = {"*.c", "*.h"} }
    }
  }
}
```

**Comment by Andrew15-5** [comment]
Thank you!
