### ISSUE TITLE
Event for Enabling and Disabling AutoSave

### ISSUE THREAD

**Issue by 1239uth** [okuuva/auto-save.nvim#45]
Would be nice to have an event or callback for when ASToggle is called or when AS is enabled and disabled, similar to how it existed before: https://github.com/pocco81/auto-save.nvim/blob/main/README.md?plain=1#L115-L116.

Thanks for maintaining the fork btw!

**Comment by primeapple** [comment]
Sorry for the long delay. This is probably a very easy thing to do. I will try to look into it!

Thanks for using the plugin :)

**Comment by okuuva** [comment]
@1239uth this should now be fixed with #46. Feel free to reopen if you run into any obvious problems with it.
