### ISSUE TITLE
Detach the fork from the original repo

### ISSUE THREAD

**Issue by primeapple** [okuuva/auto-save.nvim#61]
I think it still confuses people to see that this is still handled as a fork of the original auto-save plugin. Also I create PRs for the original one all the time and create noise there :grinning: 
And I also think it plays a role in SSO, so search engines don't rank this plugin high enough.

It may help to detach this repo from the original one. We can do this either by deleting the repo and recreating it. But this would lose all associated tickets and prs. It's also possible to contact the support about that, see https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

Since you are the owner @okuuva , could you do that?

**Comment by okuuva** [comment]
While I kinda like the fact that the github states that this is a fork and points to the original (don't want to take credit on anybody else's work), I agree. It is a hassle and tends to keep the original "alive" by creating activity there, mostly by accident. I wouldn't want to recreate the repo though, I'll contact support.

**Comment by okuuva** [comment]
Fork is now detached from the original.
