### ISSUE TITLE
Autosave without existing edit mode

### ISSUE THREAD

**Issue by xino1010** [okuuva/auto-save.nvim#62]
is there a way for auto save the file without pressing ESC or lossing the focus?
i want to save the file after 2secs after last modifications similar like visual studio code does.

Thanks you!

**Comment by primeapple** [comment]
Sure there is. 

```lua
  trigger_events = {
    defer_save = { "InsertLeave", "TextChanged", "TextChangedI" }
  },
```

Added to your config should do the job.

**Comment by xino1010** [comment]
awesome

**Comment by xino1010** [comment]
Sorry again,

After editing a line, it is saved to the second, not to the 5 seconds.

What am I doing wrong?

 ```javascript
return {
  {
    "okuuva/auto-save.nvim",
    -- version = '^1.0.0', -- see https://devhints.io/semver, alternatively use '*' to use the latest tagged release
    cmd = "ASToggle", -- optional for lazy loading on command
    event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
    opts = {
      -- your config goes here
      -- or just leave it empty :)
      trigger_events = {
        debounce_delay = 5000,
        defer_save = { "InsertLeave", "TextChanged", "TextChangedI" },
      },
    },
  },
}
```

**Comment by xino1010** [comment]
@primeapple could you take a look [here](https://github.com/okuuva/auto-save.nvim/issues/62) please?

**Comment by okuuva** [comment]
@xino1010 I'll take a look. But autoformatting is more related to https://github.com/okuuva/auto-save.nvim/issues/55 than this.

**Comment by okuuva** [comment]
Ah, and you got it sorted out already. Good :)

**Comment by xino1010** [comment]
thanks anyway!
