### ISSUE TITLE
Autosave not working without opts block

### ISSUE THREAD

**Issue by miguelcsilva** [okuuva/auto-save.nvim#65]
Hey,

I was cleaning up my configs which looked like the following:
```lua
-- auto-save.nvim
return {
  "okuuva/auto-save.nvim",
  cmd = "ASToggle", -- optional for lazy loading on command
  event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
  opts = {
    execution_message = {
      enabled = false,
    },
  },
}
```

I decided to remove the opts since I believe this alert was removed in a recent code update. The config now looked like this:
```lua
-- auto-save.nvim
return {
  "okuuva/auto-save.nvim",
  cmd = "ASToggle", -- optional for lazy loading on command
  event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
}
```

In this second version of configs, I noticed that the autosave feature stopped working. I've put back the opts and it started working again, but was wondering if it is a know problem?

Let me know if any further info helpful to reproduce.

**Comment by okuuva** [comment]
That's a feature of https://github.com/folke/lazy.nvim. Just having a plugin spec in your list of plugins doesn't automatically configure the plugin, you need to provide either `opts` or `config` if the plugin is the sort that requires a setup step: https://lazy.folke.io/spec#spec-setup

So adding either `config = true` or `opts = {}` should work.

**Comment by okuuva** [comment]
And looking at the documentation, `opts = {}` is the recommended way.
> Always use opts instead of config when possible. config is almost never needed.
```
GOOD

{ "folke/todo-comments.nvim", opts = {} },

BAD

{
  "folke/todo-comments.nvim",
  config = function()
    require("todo-comments").setup({})
  end,
},
```

**Comment by miguelcsilva** [comment]
Totally missed that. Thanks a lot for your help. Working as expected now.
